name = "pg-test"
main = "src/index.ts"
compatibility_date = "2023-08-01"

# Ensure you enable Node.js compatibility to your project
node_compat = true

[vars]
DB_URL = "postgres://reader:NWDMCE5xdipIjRrp@hh-pgsql-public.ebi.ac.uk:5432/pfmegrnargs"